config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  post "/", to: "pages#home"
  get "/analytics", to: "analytics#index"

  # session pages
  get "/auth", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  # error pages
  %w[404 422 500].each do |code|
    match code, to: "exceptions#show", code: code, via: :all
  end

  # catch all other paths and redirect them to home
  get "*path", to: "pages#redirect"
end

app/models/airtable_search.rb
class AirtableSearch
  attr_reader :terms

  def initialize(params)
    @terms = []

    params.each do |field, query|
      @terms.push "Query::#{field.titleize}".constantize.new(query)
    end

    FullQuery.create(full_query) unless terms.empty?
  end

  def find_resources
    ProjectResource.search(terms.map(&:query_string).compact)
  end

  private

  def full_query
    terms.each_with_object({}) {|term, hash| hash.merge!(term.query_data)}
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/full_query.rb
class FullQuery < ApplicationRecord
  def create(description: "", reuse: "", kind: [])
    FullQuery.create(description, reuse, kind)
  end
end

app/models/project_resource.rb
Airrecord.api_key = Rails.application.credentials.airtable_key

class ProjectResource < Airrecord::Table
  self.base_key = Rails.application.credentials.airtable_base_id
  self.table_name = "Project Resources Library"

  def self.search(query)
    begin
      all(filter: "AND(#{query.join(",")})")
    rescue StandardError
      []
    end
  end
end

app/models/query/description.rb
class Query::Description
  attr_reader :value

  def initialize(value)
    @value = value

    QueryTerm.create(field: "Description", value: value)
  end

  def query_string
    "SEARCH('#{value}', {Description})"
  end

  def query_data
    {description: value}
  end
end

app/models/query/reuse.rb
class Query::Reuse
  attr_reader :value

  def initialize(value)
    @value = value

    QueryTerm.create(field: "Reuse", value: value)
  end

  def query_string
    "OR(" + build_string + ")"
  end

  def query_data
    {reuse: value}
  end

  private

  def build_string
    str = "SEARCH('Recommended', {Reusable?})"
    return str if value == "recommended"

    str += ", SEARCH('Suggested', {Reusable?})"
    return str if value == "recommended_or_suggested"

    str += ", SEARCH('Discouraged', {Reusable?})"
    str + ", SEARCH('Unreviewed', {Reusable?})"
  end
end

app/models/query/type.rb
class Query::Type
  attr_reader :values

  def initialize(values)
    @values = values.to_hash.filter_map { |k, v| k if v == "1" }

    @values.each { |value| QueryTerm.create(field: "Type", value: value) }
  end

  def query_string
    return if values.empty?
    "OR(" + build_string + ")"
  end

  def build_string
    values
      .map { |value| "SEARCH('#{value}', {Type of Resource})" }
      .join(", ")
  end

  def query_data
    {kind: values}
  end
end

app/models/query_data.rb
class QueryData
  def latest_queries
    @latest_queries ||= FullQuery.last(10)
  end

  def description_data
    @description_data ||= process_count_data(
      QueryTerm.description_by_count
    )
  end

  def type_data
    @type_data ||= process_count_data(
      QueryTerm.type_by_count
    )
  end

  private

  def process_count_data(data)
    data.map { |key, value| {value: key, count: value} }
  end
end

app/models/query_term.rb
class QueryTerm < ApplicationRecord
  def self.description_by_count
    where(field: "Description").where.not(value: [nil, ""]).select("value").group(:value).order(count: :desc).count
  end

  def self.type_by_count
    where(field: "Type").select(:value).group(:value).order(count: :desc).count
  end
end

app/models/session.rb
class Session
  def initialize(code)
    @code = code
  end

  def email
    token[0]["email"]
  end

  private

  def token
    @token ||=
      if Rails.env.development?
        JWT.decode response_body[:access_token], nil, false
      else
        JWT.decode response_body[:access_token], nil, true, jwks: jwt_keys, algorithm: "RS256"
      end
  end

  def jwt_keys
    @jwt_keys ||= JSON.parse(
      Net::HTTP.get(URI("https://uaa.fr.cloud.gov/token_keys")),
      symbolize_names: true
    )
  end

  def uri
    @uri ||= URI(ENV["TOKEN_URI"])
  end

  def response_body
    JSON.parse(response.body, symbolize_names: true)
  end

  def response
    @response ||= Net::HTTP.post_form(uri, request_params)
  end

  def request_params
    {
      code: @code,
      grant_type: "authorization_code",
      response_type: "token",
      client_id: ENV["UAA_CLIENT_ID"] || Rails.application.credentials.uaa_client_id,
      client_secret: ENV["UAA_SECRET"] || Rails.application.credentials.uaa_client_secret,
      redirect_uri: ENV["REDIRECT_URI"]
    }
  end
end

app/controllers/analytics_controller.rb
class AnalyticsController < ApplicationController
  before_action :require_user!

  def index
    @query_data = QueryData.new
  end

  def require_user!
    return if helpers.user_signed_in?
    return if Rails.configuration.x.bypass_auth? == true
    redirect_to root_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_forgery_protection if: -> { Rails.configuration.x.bypass_auth }
end

app/controllers/exceptions_controller.rb
class ExceptionsController < ApplicationController
  def show
    render page, status: status_code
  end

  private

  def status_code
    params[:code] || 500
  end

  def page
    status_code.to_s
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @search = search_params
    @results = AirtableSearch.new(search_params).find_resources
  end

  def redirect
    redirect_to root_path
  end

  private

  def search_params
    return {} unless params[:search]

    params.require(:search).permit :description, :reuse, type: {}
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    session[:email] = auth_info.email

    redirect_to root_path
  end

  def destroy
    reset_session

    redirect_to root_path
  end

  private

  def auth_info
    @auth_info || Session.new(params[:code])
  end
end

app/helpers/analytics_helper.rb
module AnalyticsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    session[:email] = "ci@example.com" if Rails.configuration.x.bypass_auth == true 
    @current_user ||= session[:email]
  end

  def user_signed_in?
    !!current_user
  end
end

app/helpers/pages_helper.rb
module PagesHelper
  def formatted_use
    {
      Recommended: "Yes",
      Suggested: "Needs some work",
      Discouraged: "Needs work",
      Unreviewed: "Unknown"
    }.with_indifferent_access
  end

  def resource_types
    [
      "Template",
      "Example",
      "Training",
      "Guide",
      "Case Study",
      "Report"
    ]
  end

  def uaa_login_url
    uri.to_s
  end

  private

  def uri
    is_development? ? URI::HTTP.build(uri_params) : URI::HTTPS.build(uri_params)
  end

  def uri_params
    {
      host: ENV["UAA_HOST"],
      path: ENV["UAA_PATH"],
      port: ENV["UAA_PORT"],
      query: query
    }
  end

  def query
    URI.encode_www_form({
      client_id: client_id,
      response_type: "code",
      redirect_uri: ENV["REDIRECT_URI"],
      state: state
    })
  end

  def client_id
    ENV["UAA_CLIENT_ID"] || Rails.application.credentials.uaa_client_id
  end

  def state
    SecureRandom.hex
  end

  def is_development?
    Rails.env.development?
  end
end

app/views/analytics/_description_data.html.erb
<tr class="flex-row">
  <td data-sort-value=<%= description_data[:count] %>>
    <%= description_data[:count] %>
  </td>
  <td><%= description_data[:value] %></td>
</tr>

app/views/analytics/_description_table.html.erb
<div>
  <table class="usa-table site-table-responsive site-table-simple">
    <caption>
      Description searches by count
    </caption>
    <thead>
      <tr>
        <th scope="col" role="columnheader" data-sortable> Count </th>
        <th scope="col" role="columnheader"> Description </th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "description_data", collection: @query_data.description_data %>
    </tbody>
  </table>
</div>

app/views/analytics/_latest_query.html.erb
<tr class="flex-row">
  <td><%= latest_query.description %></td>
  <td><%= latest_query.reuse %></td>
  <td><%= latest_query.kind&.join(", ") %></td>
</tr>

app/views/analytics/_latest_table.html.erb
<div>
  <table class="usa-table site-table-responsive site-table-simple">
    <caption>
      Latest searches
    </caption>
    <thead>
      <tr>
        <th scope="col" role="columnheader"> Description </th>
        <th scope="col" role="columnheader"> Reusability </th>
        <th scope="col" role="columnheader"> Type </th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "latest_query", collection: @query_data.latest_queries %>
    </tbody>
  </table>
</div>

app/views/analytics/_type_data.html.erb
<tr class="flex-row">
  <td><%= type_data[:count] %></td>
  <td><%= type_data[:value] %></td>
</tr>

app/views/analytics/_type_table.html.erb
<div>
  <table class="usa-table site-table-responsive site-table-simple">
    <caption>
      Types of resources by count
    </caption>
    <thead>
      <tr>
        <th scope="col" role="columnheader"> Count </th>
        <th scope="col" role="columnheader"> Type </th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "type_data", collection: @query_data.type_data %>
    </tbody>
  </table>
</div>

app/views/analytics/index.html.erb
<div>
  <div class="display-flex flex-justify">
      <%= render partial: "latest_table" %>
      <%= render partial: "type_table" %>
  </div>
  <%= render partial: "description_table" %>
</div>

app/views/application/_header.html.erb
<header class="usa-header usa-header--basic">
  <div class="grid-container">
    <div class="grid-row">
      <div class="usa-logo grid-col-6" id="basic-logo">
        <%= link_to "Project Resources", root_path, class: "usa-logo__text font-heading-xl" %>
      </div>
      <div class="grid-row grid-col-6 grid-gap flex-align-center flex-justify-end">
        <% if user_signed_in? %>
          <div class="grid-col-auto">
            <%= current_user %>
          </div>
          <div class="grid-col-auto">
            <%= button_to "Log out", logout_path, class: "usa-button usa-button--accent-warm", method: :delete %>
          </div>
        <% else %>
          <div class="grid-col-auto">
            <%= link_to "Log in", uaa_login_url, class: "usa-button usa-button--accent-warm" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</header>

app/views/application/_usa_banner.html.erb
<a class="usa-skipnav" href="#main-content">Skip to main content</a>
<section class="usa-banner" aria-label="Official government website">
  <div class="usa-accordion">
    <header class="usa-banner__header">
      <div class="usa-banner__inner">
        <div class="grid-col-auto">
          <%= image_tag "uswds/dist/img/us_flag_small.png", alt: "U.S. flag", class: "usa-banner__header-flag" %>
        </div>
        <div class="grid-col-fill tablet:grid-col-auto">
          <p class="usa-banner__header-text">
            An official website of the United States government
          </p>
          <p class="usa-banner__header-action" aria-hidden="true">
            Here’s how you know
          </p>
        </div>
        <button
          class="usa-accordion__button usa-banner__button"
          aria-expanded="false"
          aria-controls="gov-banner"
        >
          <span class="usa-banner__button-text">Here’s how you know</span>
        </button>
      </div>
    </header>
    <div class="usa-banner__content usa-accordion__content" id="gov-banner">
      <%= javascript_tag nonce: true do %>
        document.getElementById('gov-banner').setAttribute('hidden', '');
      <% end %>
      <div class="grid-row grid-gap-lg">
        <div class="usa-banner__guidance tablet:grid-col-6">
          <%= image_tag "uswds/dist/img/icon-dot-gov.svg", role: "img", "aria-hidden": true, class: "usa-banner__icon usa-media-block__img" %>
          <div class="usa-media-block__body">
            <p>
              <strong> Official websites use .gov </strong>
              <br />
              A <strong>.gov</strong> website belongs to an official government
              organization in the United States.
            </p>
          </div>
        </div>
        <div class="usa-banner__guidance tablet:grid-col-6">
          <%= image_tag "uswds/dist/img/icon-https.svg", role: "img", "aria-hidden": true, class: "usa-banner__icon usa-media-block__img" %>
          <div class="usa-media-block__body">
            <p>
              <strong> Secure .gov websites use HTTPS </strong>
              <br />
              A <strong>lock</strong> (
              <span class="icon-lock"
                ><svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="52"
                  height="64"
                  viewBox="0 0 52 64"
                  class="usa-banner__lock-image"
                  role="img"
                  aria-labelledby="banner-lock-title-default banner-lock-description-default"
                  focusable="false"
                >
                  <title id="banner-lock-title-default">Lock</title>
                  <desc id="banner-lock-description-default">A locked padlock</desc>
                  <path
                    fill="#000000"
                    fill-rule="evenodd"
                    d="M26 0c10.493 0 19 8.507 19 19v9h3a4 4 0 0 1 4 4v28a4 4 0 0 1-4 4H4a4 4 0 0 1-4-4V32a4 4 0 0 1 4-4h3v-9C7 8.507 15.507 0 26 0zm0 8c-5.979 0-10.843 4.77-10.996 10.712L15 19v9h22v-9c0-6.075-4.925-11-11-11z"
                  /></svg
              ></span>
              ) or <strong>https://</strong> means you’ve safely connected to
              the .gov website. Share sensitive information only on official,
              secure websites.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/exceptions/404.html.erb
<section>
  <h1 class="h3 accent-after accent-magenta content-none--before">
    The page you were looking for doesn't exist (404)
  </h1>
  <h2 class="border-0">You may have mistyped the address or the page may have moved.</h2>
  <p class="h2 margin-top-4">
    If you are the application owner check the logs for more information.
  </p>
</section>

app/views/exceptions/422.html.erb
<section>
  <h1 class="h3 accent-after accent-magenta content-none--before">
    The change you wanted was rejected (422)
  </h1>
  <h2 class="border-0">Maybe you tried to change something you didn't have access to.</h2>
  <p class="h2 margin-top-4">
    If you are the application owner check the logs for more information.
  </p>
</section>

app/views/exceptions/500.html.erb
<section>
  <h1 class="h3 accent-after accent-magenta content-none--before">
    We're sorry, but something went wrong. (500)
  </h1>
  <p class="h2 margin-top-4">
    If you are the application owner check the logs for more information.
  </p>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>ProjectResourceSearch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
        <%= render "application/usa_banner" %>
        <%= render "application/header" %>
    <main id="main-content">
      <div class="grid-container usa-section">
        <%= yield %>
      </div>
    </main>

  </body>
</html>

app/views/pages/_result.html.erb
<tr class="flex-row">
  <td><%= link_to result.fields["Resource Name"], result.fields["Link"]["url"], target: "_blank" %></td>
  <td><%= result.fields["Description"] %></td>
  <td> 
    <%= result.fields["Type of Resource"]&.join(", ") %>
  </td>
  <td><%= result.fields["File Type"] %></td>
  <td><%= formatted_use[result.fields["Reusable?"]] %></td>
  <td><%= result.fields["Approved to share?"] %>
</tr>

app/views/pages/_result_table.html.erb
<div>
  <table class="usa-table site-table-responsive site-table-simple">
    <caption>
      Airtable search results with the above parameters
    </caption>
    <thead>
      <tr>
        <th scope="col" role="columnheader"> Resource name </th>
        <th scope="col" role="columnheader"> Description </th>
        <th scope="col" role="columnheader"> Type of resource </th>
        <th scope="col" role="columnheader"> File type </th>
        <th scope="col" role="columnheader"> Ready to use? </th>
        <th scope="col" role="columnheader"> Approved for: </th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "result", collection: @results %>
    </tbody>
  </table>
</div>

app/views/pages/_search.html.erb
<section aria-label="descripton search">
  <h2>Find resources that suit your current project or need</h2>

  <%= form_with scope: :search, class: "usa-search usa-search--big grid-container" do |form| %>
    <div class="grid-row flex-align-center">
      <div class="grid-col-fill">
        <%= form.label  "description", "Description field", class: "padding-right-2" %>
        <%= form.text_field :description, value: @search[:description], class: "usa-input" %>
      </div>

      <div class="grid-col-auto">
        <fieldset class="usa-fieldset">
          <legend class="usa-legend">Resource Reusability</legend>
          <%= form.radio_button :reuse,
            "recommended",
            checked: @search[:reuse] == "recommended",
            class: "usa-radio__input"
          %>
          <%= form.label :reuse, "Recommended", value: "recommended", class: "usa-radio__label"  %>
          
          <%= form.radio_button :reuse,
            "recommended_or_suggested",
            checked: @search[:reuse] == "recommended_or_suggested",
            class: "usa-radio__input"
          %>
          <%= form.label :reuse, "Recommended or suggested", value: "recommended_or_suggested", class: "usa-radio__label"  %>
          
          <%= form.radio_button :reuse,
            "all",
            checked: @search[:reuse] == "all",
            class: "usa-radio__input"
          %>
          <%= form.label :reuse, "All resources", value: "all", class: "usa-radio__label" %>
        </fieldset>
      </div>
    </div>

    <div class="grid-row flex-align-center margin-1">
        <%= field_set_tag "Resource Type", class: "usa-fieldset grid-row", name: :type do%>
          <% resource_types.each do |type| %>
            <%= fields_for "search[type]" do |type_form| %>
              <div class="usa-checkbox padding-05">
                <%= type_form.check_box type,
                 value: type,
                 class: "usa-checkbox__input",
                 checked: @search.dig(:type, type) == "1" %>
                <%= type_form.label type, type, class: "usa-checkbox__label"  %>
             </div>
            <% end %>
          <% end %>
        <% end %>
    </div>

    <%= form.submit "Search", class: "usa-button" %>
  <% end %>
</section>

app/views/pages/home.html.erb
<div>
  <% if user_signed_in? %>
    <%= render partial: "search" %>

    <% if @results.empty? %>
      <div>
        <h2>No results fit that search.</h2>
      </div>
    <% else %>
      <%= render partial: "result_table" %> 
    <% end %>
  <% else %>
    <h2>Please log in to search library.</h2>
  <% end %>
</div>